applications:
  nginx:
    type: custom
    template: ./Dockerfile
    ports:
      80: 80
      2222: 22
    volumes:
      .: /home/app
    links: [mysql, redis]
  redis:
    type: index
    image: swcc/docker-redis
  mysql:
    type: custom
    template: ./mysql/Dockerfile
    volumes:
      /tmp/mysql_st: /var/lib/mysql
