language: ruby
rvm:
  - 2.1.3
  - 2.0.0
  - 1.9.3
before_script:
  - cp config/database_ci.yml config/database.yml
  - "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS st_test DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
  - "mysql -uroot -e \"GRANT ALL PRIVILEGES ON st_test.* TO 'st_test'@'localhost' IDENTIFIED BY 'st_test';\""
