development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: st_dev
  username: st_dev
  password: st_dev
  host: mysql
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: st_test
  username: st_dev
  password: st_dev
  host: mysql
  port: 3306

preprod:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: <%=ENV['PREPROD_ST_DB_NAME']%>
  username: <%=ENV['PREPROD_ST_DB_USERNAME']%>
  password: <%=ENV['PREPROD_ST_DB_PASSWORD']%>
  host: <%=ENV['PREPROD_ST_DB_HOST']%>
  port: <%=ENV['PREPROD_ST_DB_PORT']%>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: <%=ENV['ST_DB_NAME']%>
  username: <%=ENV['ST_DB_USERNAME']%>
  password: <%=ENV['ST_DB_PASSWORD']%>
  host: <%=ENV['ST_DB_HOST']%>
  port: <%=ENV['ST_DB_PORT']%>

