source "http://api.berkshelf.com"

cookbook 'openssh', '~> 1.3.2'
cookbook 'rvm', github: 'fnichol/chef-rvm'
# Because of this : https://gist.github.com/jnevelson/10211026
cookbook 'monkey', '~> 1.0.1'
cookbook 'nginx', github: 'popox/nginx', :ref => '363fedf2ecff56291e3f6459c75e033ae275188d'
cookbook 'mysql', '~> 5.2.2'
cookbook 'redisio', '~> 1.7.1'